services:
  shop_api_backend:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - shop_api-db
  shop_api-db:
    image: 'postgres:14'
    env_file: .env
    environment:
      POSTGRES_DB: '${NAME_DB}'
      POSTGRES_USER: '${USER_DB}'
      POSTGRES_PASSWORD: '${PASSWORD_DB}'
    volumes:
      - "shop_api-data:/var/lib/postgresql/data"
volumes:
  shop_api-data:

